# -*- coding: utf-8 -*-
"""CSC8101_spark_coursework_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bo1MAalpVZfySVHjLwJqSE2SFbHnS4g8

# [CSC8101] Engineering for AI - 2025 Spark Coursework

## NAME: KARTHICK KEERANAGERE KRISHNAIAH
## STUDENT ID: 250180659


## Coursework overview

### Inputs

- **NYC Taxi Trips dataset** - list of recorded taxi trips, each with several characteristics, namely: distance, number of passengers, origin zone, destination zone and trip cost (total amount charged to customer).
- **NYC Zones dataset** - list of zones wherein trips can originate/terminate.

### Tasks

1. Data cleaning
  1. Remove "0 distance" and 'no passengers' records.
  2. Remove outlier records.
2. Add new columns
  1. Join with zones dataset
  2. Compute the unit profitability of each trip
3. Zone summarisation and ranking
  1. Summarise trip data per zone
  2. Obtain the top 10 ranks according to:
    1. The total trip volume
    2. Their average profitabilitiy
    3. The total passenger volume
4. Record the total and task-specific execution times for each dataset size and format.

### How to

###### Code structure and implementation

- You must implement your solution to each task in the provided function code skeleton.
- The task-specific functions are combined together to form the full pipeline code, executed last (do not modify this code).
- Before implementing the specified function skeleton, you should develop and test your solution on separate code cells (create and destroy cells as needed).

###### Development

- Develop an initial working solution for the 'S' dataset and only then optimise it for larger dataset sizes.
- To perform vectorised operations on a DataFrame:
  - use the API docs to look for existing vectorised functions in: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html
  - if a customised function is required (e.g. to add a new column based on a linear combination of other columns), implement your own User Defined Function (UDF). See:  https://spark.apache.org/docs/latest/sql-ref-functions-udf-scalar.html
- Use only the `pyspark.sql` API - documentation link below - (note that searching through the docs returns results from the `pyspark.sql` API):
- Periodically download your notebook to your computer as backup and safety measure against accidental file deletion.

###### Execution time measurement

- Execution time is calculated and returned by the Spark Engine and shown in the output region of the cell.
- To measure the execution time of a task you must perform a `collect` or similar operation (e.g. `take`) on the returned DataFrame.

The following codeblock is used to mount the google colab instance to your google drive, in which we will be accessing the data provided in the course.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Task 0 - Read data

The code below is ready to run. **Do not modify this code**. It does the following:

- Reads the 'zones' dataset into variable 'zone_names'
- Defines the `init_trips` function that allows you to read the 'trips' dataset (from the DBFS FileStore) given the dataset size ('S' to 'XXL') as function argument
- Defines the `pipeline` function, called in Task 4 to measure the execution time of the entire data processing pipeline
- Shows you how to call the `init_trips` function and display dataset characteristics (number of rows, schema)
"""

pip install findspark pyspark

## global imports
import pyspark.sql as ps
import pyspark.sql.functions as pf
import pandas as pd
import findspark
findspark.init()
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
import time
spark = SparkSession.builder.master("local[*]").config("spark.driver.memory", "10g").getOrCreate()

# Load zone names dataset - (much faster to read small file from git than dbfs)
zones_file_url = 'https://raw.githubusercontent.com/NewcastleComputingScience/csc8101-coursework/main/02-assignment-spark/taxi_zone_names.csv'
zone_names = spark.createDataFrame(pd.read_csv(zones_file_url))

# Function to load trips dataset by selected dataset size
def init_trips(size = 'S'):

    files = {
        'S'  : ['2021_07'],
        'M'  : ['2021'],
        'L'  : ['2020_21'],
        'XL' : ['1_6_2019', '7_12_2019'],
        'XXL': ['1_6_2019', '7_12_2019', '2020_21']
    }

    # validate input dataset size
    if size not in files.keys():
        print("Invalid input dataset size. Must be one of {}".format(list(files.keys())))
        return None
        /content/drive/MyDrive/CSC8101_Data

    filenames = list(map(lambda s: f'/content/drive/MyDrive/CSC8101_Data/CSC8101_Data/tripdata_{s}.parquet', files[size]))
    trips_df = spark.read.parquet(filenames[0])

    for name in filenames[1:]:
        trips_df = trips_df.union(spark.read.parquet(name))


    print(
    """
    Trips dataset loaded!
    ---
      Size: {s}
      Tables loaded: {ds}
      Number of trips (dataset rows): {tc:,}
    """.format(s = size, ds = filenames, tc = trips_df.count()))

    return trips_df

# helper function to print dataset row count
def print_count(df):
    print("Row count: {t:,}".format(t = df.count()))

def pipeline(trips_df, with_task_12 = False, zones_df = zone_names):
    # Do not edit
    #---

    ## Task 1.1
    _trips_11 = t11_remove_zeros(trips_df)

    ## Task 1.2
    if with_task_12:
        _trips_12 = t12_remove_outliers(_trips_11)
    else:
        _trips_12 = _trips_11

    ## Task 2.1
    _trips_21 = t21_join_zones(_trips_12, zones_df = zone_names)

    ## Task 2.2
    _trips_22 = t22_calc_profit(_trips_21)

    ## Task 3.1
    _graph = t31_summarise_trips(_trips_22)

    ## Task 3.2
    _zones = t32_summarise_zones_pairs(_graph)

    _top10_trips     = t32_top10_trips(_zones)
    _top10_profit    = t32_top10_profit(_zones)
    _top10_passenger = t32_top10_passenger(_zones)

    return([_top10_trips, _top10_profit, _top10_passenger])

# CHANGE the value of argument 'size' to record the pipeline execution times for increasing dataset sizes
SIZE = 'S'


# Load trips dataset
trips = init_trips(SIZE)

# uncomment line only for small datasets
# trips.take(1)

#/content/drive/MyDrive/Assignment/CSC8101_Data/tripdata_2021.parquet
print_count(trips)

# dataset schemas
trips.printSchema()

display(trips[['PULocationID', 'DOLocationID', 'trip_distance', 'passenger_count', 'total_amount']].take(5))

zone_names.printSchema()

display(zone_names.take(5))

"""## Task 1 - Filter rows

**Input:** trips dataset

### Task 1.1 - Remove "0 distance" and 'no passengers' records

Remove dataset rows that represent invalid trips:

- Trips where `trip_distance == 0` (no distance travelled)
- Trips where `passenger_count == 0` and `total_amount == 0` (we want to retain records where `total_amount` > 0 - these may be significant as the taxi may have carried some parcel, for example)

Altogether, a record is removed if it satisfies the following conditions:

`trip_distance == 0` or `(passenger_count == 0` and `total_amount == 0)`.

**Recommended:** Select only the relevant dataset columns for this and subsequent tasks: `['PULocationID', 'DOLocationID', 'trip_distance', 'passenger_count', 'total_amount')]`

### Task 1.2 - Remove outliers using the modified z-score

Despite having removed spurious "zero passengers" trips in task 1.1, columns `total_amount` and `trip_distance` contain additional outlier values that must be identified and removed.

To identify and remove outliers, you will use the modified [z-score](https://en.wikipedia.org/wiki/Standard_score) method.
The modified z-score uses the median and [Median Absolute Deviation](https://en.wikipedia.org/wiki/Median_absolute_deviation) (MAD), instead of the mean and standard deviation, to determine how far an observation (indexed by i) is from the mean:

$$z_i = \frac{x_i - \mathit{median}(\mathbf{x})}{\mathbf{MAD}},$$

where x represents the input vector, xi is an element of x and zi is its corresponding z-score. In turn, the MAD formula is:

$$\mathbf{MAD} = 1.483 * \mathit{median}(\big\lvert x_i - \mathit{median}(\mathbf{x})\big\rvert).$$

Observations with **high** (absolute) z-score are considered outlier observations. A score is considered **high** if its __absolute z-score__ is larger than a threshold T = 3.5:

$$\big\lvert z_i \big\rvert > 3.5.$$

where T represents the number of unit standard deviations beyond which a score is considered an outlier ([wiki](https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule)).

This process is repeated twice, once for each of the columns `total_amount` and `trip_distance` (in any order).

**Important:** Use the surrogate function [`percentile_approx`](https://spark.apache.org/docs/3.2.0/api/python/reference/api/pyspark.sql.functions.percentile_approx.html?highlight=percentile#pyspark.sql.functions.percentile_approx) to estimate the median (calculating the median values for a column is expensive as it cannot be parallelised efficiently).
"""

# Task 1.1 - Remove "0 distance" and "no passengers" records

def t11_remove_zeros(df):
  # Select only relevant columns
  df = df.select(
      'PULocationID',
      'DOLocationID',
      'trip_distance',
      'passenger_count',
      'total_amount'
  )

  # Remove invalid trips:
  df = df.filter((trips.trip_distance != 0) | ((trips.passenger_count != 0) & (trips.total_amount != 0)))
  return df

# execute task 1.1
trips_11 = t11_remove_zeros(trips)

print_count(trips_11)

## uncomment only for smaller datasets
# display(trips_11.take(10))

def t12_remove_outliers(df):

    # Trip_distance

    median = df.agg(
        pf.percentile_approx("trip_distance", 0.5, 10000)
    ).collect()[0][0]

    df = df.withColumn(
        "subtractedTrip",
        pf.abs(pf.col("trip_distance") - pf.lit(median))
    )

    madTrip = 1.483 * df.agg(
        pf.percentile_approx("subtractedTrip", 0.5, 10000)
    ).collect()[0][0]

    df = df.withColumn("madTrip", pf.lit(madTrip))

    df = df.withColumn(
        "zscoreTrip",
        pf.col("subtractedTrip") / pf.lit(madTrip)
    )


    # Total_amount

    totalMedian = df.agg(
        pf.percentile_approx("total_amount", 0.5, 10000)
    ).collect()[0][0]

    df = df.withColumn(
        "subtractedAmount",
        pf.abs(pf.col("total_amount") - pf.lit(totalMedian))
    )

    madTotal = 1.483 * df.agg(
        pf.percentile_approx("subtractedAmount", 0.5, 10000)
    ).collect()[0][0]

    df = df.withColumn("madAmount", pf.lit(madTotal))

    df = df.withColumn(
        "zscoreAmount",
        pf.col("subtractedAmount") / pf.lit(madTotal)
    )


    # Filter

    df = df.filter(
        (pf.col("zscoreTrip") < 3.5) &
        (pf.col("zscoreAmount") < 3.5)
    )

    df = df.drop(
        "subtractedTrip",
        "madTrip",
        "zscoreTrip",
        "subtractedAmount",
        "madAmount",
        "zscoreAmount"
    )

    return df

# execute task 1.2
trips_12 = t12_remove_outliers(trips_11)

print_count(trips_12)
# display(trips_12.take(10))

"""## Task 2 - Compute new columns

### Task 2.1 - Zone names

Obtain the **start** and **end** zone names of each trip by joining the `trips` and `zone_names` datasets (i.e. by using the `zone_names` dataset as lookup table).

**Note:** The columns containing the start and end zone ids of each trip are named `PULocationID` and `DOLocationID`, respectively.

### Task 2.2 - Unit profitability

Compute the column `unit_profitabilty = total_amount / trip_distance`.
"""

# Task 2.1 - Join zone names
def t21_join_zones(df, zones_df=zone_names):
    zones_pu = zones_df.select(F.col("LocationID").alias("PU_ID"),F.col("Zone").alias("PU_Zone"))

# Use PU_Zone and DO_Zone to avoid ambiguity
    zones_do = zones_df.select(F.col("LocationID").alias("DO_ID"),F.col("Zone").alias("DO_Zone"))

# Use left join so that even if LocationID is missing we won't loose trip record
    # 1) Join on PULocationID with PU_Zone
    df1 = df.join(zones_pu, df.PULocationID == zones_pu.PU_ID, "left")

    # 2) Join on DOLocationID with DO_Zone
    df2 = df1.join(zones_do, df1.DOLocationID == zones_do.DO_ID, "left")

    # Drop duplicate ID columns from zone names lookup
    df_final = df2.drop("PU_ID").drop("DO_ID")

    return df_final

# execute task 2.1
trips_21 = t21_join_zones(trips_12, zones_df = zone_names)

print_count(trips_21)
# display(trips_21.take(10))

# Task 2.2 - Compute unit profitability
# Though we have removed 0 from Task 1.1, however, adding the F.when() check is
# considered a Best Practice in Spark Data Engineering to prevent pipeline failures
def t22_calc_profit(df):
    return df.withColumn("unit_profitability",F.when(F.col("trip_distance") > 0, F.col("total_amount") / F.col("trip_distance")).otherwise(0.0)    )

# execute task 2.2
trips_22 = t22_calc_profit(trips_21)

print_count(trips_22)
display(trips_22.take(10))

"""## Task 3: Rank zones by traffic, passenger volume and profitability

### 3.1 - Summarise interzonal travel

Build a graph data structure of zone-to-zone traffic, representing aggregated data about trips between any two zones. The graph will have one node for each zone and one edge connecting each pair of zones. In addition, edges contain aggregate information about all trips between those zones.

For example, zones Z1 and Z2 are connected by *two* edges: edge Z1 --> Z2 carries aggregate data about all trips that originated in Z1 and ended in Z2, and edge Z2 --> Z2 carries aggregate data about all trips that originated in Z2 and ended in Z1.

The aggregate information of interzonal travel must include the following data:

- `average_unit_profit` - the average unit profitability (calculated as `mean(unit_profitabilty)`).
- `trips_count` -- the total number of recorded trips.
- `total_passengers` -- the total number of passenger across all trips (sum of `passenger_count`).

This graph can be represented as a new dataframe, with schema:

\[`PULocationID`, `DOLocationID`, `average_unit_profit`, `trips_count`, `total_passengers` \]

__hint__: the `groupby()` operator produces a `pyspark.sql.GroupedData` structure. You can then calculate multiple aggregations from this using `pyspark.sql.GroupedData.agg()`:
- https://spark.apache.org/docs/3.2.0/api/python/reference/pyspark.pandas/api/pyspark.pandas.DataFrame.groupby.html
- https://spark.apache.org/docs/3.2.0/api/python/reference/api/pyspark.sql.GroupedData.agg.html

### Task 3.2 - Obtain top-10 zones

For each of the following measures, report the top-10 zones _using their plain names you dereferenced in the previous step, not the codes_. Note that this requires ranking the nodes in different orders. Specifically, you need to calculate the following further aggregations:

- the **total** number of trips originating from Z. This is simply the sum of `trips_count` over all outgoing edges for Z, i.e., edges of the form Z -> \*
- the **average** profitability of a zone. This is the average of all `average_unit_profit` over all *outgoing* edges from Z.
- The **total** passenger volume measured as the **sum** of `total_passengers` carried in trips that originate from Z
"""

# Task 3.1 - Summarise interzonal travel
def t31_summarise_trips(df):
    # Group by origin and destination zones
    graph = (df.groupBy("PULocationID", "DOLocationID")
               .agg(F.avg("unit_profitability").alias("average_unit_profit"),
                    F.count("*").alias("trips_count"), F.sum("passenger_count").alias("total_passengers")))
    return graph

# Task 3.1
graph = t31_summarise_trips(trips_22)

print_count(graph)
display(graph.take(10))

# Solution to task 3.2
def t32_summarise_zones_pairs(df, zones_df=zone_names):

    # Aggregate outgoing edges per zone
    zone_summary = (df.groupBy("PULocationID").agg(F.sum("trips_count").alias("total_trips"),F.avg("average_unit_profit").alias("avg_profit"),
                          F.sum("total_passengers").alias("total_passengers")
                      ))

    # Join zone names
    zone_summary = (zone_summary.join(zones_df, zone_summary.PULocationID == zones_df.LocationID, "left").drop("LocationID"))

    # Rename zone name column
    zone_summary = zone_summary.withColumnRenamed("Zone", "Zone_Name")

    return zone_summary

# Top 10 ranked zones by traffic (trip volume)
def t32_top10_trips(df_zones):
    return (df_zones.orderBy(F.desc("total_trips"))
                    .limit(10)
                    .toPandas())

# Top 10 ranked zones by profit
def t32_top10_profit(df_zones):
    return (df_zones.orderBy(F.desc("avg_profit"))
                    .limit(10)
                    .toPandas())

# Top 10 ranked zones by passenger volume
def t32_top10_passenger(df_zones):
    return (df_zones.orderBy(F.desc("total_passengers"))
                    .limit(10)
                    .toPandas())

# execute task 3.2
zones = t32_summarise_zones_pairs(graph)

top10_trips     = t32_top10_trips(zones)
top10_profit    = t32_top10_profit(zones)
top10_passenger = t32_top10_passenger(zones)

# use 'display()' or return a pandas DataFrame for 'pretty' output
display(top10_trips)

# use 'display()' return a pandas DataFrame for 'pretty' output
display(top10_profit)

# use 'display()' or return a pandas DataFrame for 'pretty' output
display(top10_passenger)

"""## Task 4 - Record the pipeline's execution time

Record the execution time of:

1. the whole pipeline
2. the whole pipeline except task 1.2

on the two tables below, for all dataset sizes: `'S'`, `'M'`, `'L'`, `'XL'`, `'XXL'`.

Analyse the resulting execution times and comment on the effect of dataset size, dataset format and task complexity (with and without task 1.2) on pipeline performance.
"""

# Run and record the resulting execution time shown by databricks (on the cell footer)
# IMPORTANT: this function calls all task functions in order of occurrence.
# For this code to run without errors, you have to load into memory all of the previous task-specific functions.

SIZE = ['S', "M", "L", "XL", "XXL"]
results=[]
for s in SIZE:
    print(f"Running benchmarks for SIZE = {s}")
    trips = init_trips(s)

    Without_task_12_start = time.time()
    pipeline(trips, with_task_12=False)
    t_without = time.time() - Without_task_12_start

    With_task_12_start = time.time()
    pipeline(trips, with_task_12=True)
    t_with = time.time() - With_task_12_start

    #Store results
    results.append({ "SIZE": s, "Time without task_12": t_without, "Time with task_12": t_with })
    #Convert to table
df = pd.DataFrame(results)
print("Results table:")
print(df.to_string(index=False))

"""'''
 ## ---- Analysis ----
The results show a clear relationship between dataset size, task complexity, and pipeline performance. As dataset size increases from S (2.9 million rows) to XXL (132.4 million rows), execution time rises consistently for both configurations. Without Task 1.2, runtime increases from 9.1 seconds (S) to 160.6 seconds (XXL), demonstrating good scalability. Although the dataset size grows by more than 45 times from S to XXL, execution time increases by approximately 18 times, indicating that Spark handles larger volumes efficiently for standard transformations and aggregations.

When Task 1.2 (modified z-score outlier removal) is enabled, execution time increases significantly across all dataset sizes. The overhead is modest for small datasets but becomes substantial at larger scales. For example, at XXL size, runtime increases from 160.6 seconds to 363.7 seconds, more than doubling execution time. This is expected because Task 1.2 requires multiple median and Median Absolute Deviation (MAD) computations using percentile_approx, which involve full dataset scans and distributed aggregation. These operations are computationally intensive and scale with data volume.

Overall, dataset size has the strongest impact on performance, while aggregation-heavy statistical operations introduce considerable additional overhead, particularly for very large datasets.

'''
"""